version: "3.1"
services:
  webserver:
    build: .
    container_name: app-distribution
    ports:
     - "8999:80"
    volumes:
      - "./apps:/var/www/html/apps"
    environment:
      - APP_HOST=localhost
      - DEVELOPER_EMAIL=aleksey@company.name
      - DEBUG=true
